In [1]:
# Import Numpy & PyTorch
import numpy as np
import torch
import torch.nn as nn

In [2]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37],[69, 96, 70],
                   [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69,96, 70],
                   [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96,70]], dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119],
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]],dtype='float32')

In [3]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [4]:
# Import tensor dataset & data loader
from torch.utils.data import TensorDataset, DataLoader

In [5]:
# Define dataset
train_ds = TensorDataset(inputs,targets)
train_ds[0:5]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.]]))

In [6]:
# Define data loader
batch_size = 4
train_dl = DataLoader(train_ds,batch_size,shuffle=True)
next(iter(train_dl))

[tensor([[ 69.,  96.,  70.],
         [ 73.,  67.,  43.],
         [ 87., 134.,  58.],
         [ 91.,  88.,  64.]]), tensor([[103., 119.],
         [ 56.,  70.],
         [119., 133.],
         [ 81., 101.]])]

In [7]:
# Define model
model = nn.Linear(3,2) #3 inputs and 2 outputs
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.0322, -0.3619, -0.2570],
        [-0.4793,  0.5179,  0.4321]], requires_grad=True)
Parameter containing:
tensor([-0.5416,  0.1116], requires_grad=True)


In [8]:
#Obtain Parameters
opt = torch.optim.SGD(model.parameters(),lr=1e-4)

In [9]:
# Import nn.functional
import torch.nn.functional as F

In [10]:
# Define loss function
loss_fn = F.mse_loss

In [11]:
# Calculate loss
loss = loss_fn(model(inputs),targets)
print(loss)

tensor(10386.5156, grad_fn=<MseLossBackward0>)


In [12]:
#Obtain Parameters
opt = torch.optim.SGD(model.parameters(),lr=1e-4)

In [14]:
# Train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):
    for epoch in range(num_epochs):
        for xb, yb in train_dl:
            #Generate Predictions
            pred = model(xb)
            loss = loss_fn(pred,yb)
            #Perform Gradient Descent
            loss.backward()
            opt.step()
            #set the gradients to zero
            opt.zero_grad()
    print('Training Loss: ', loss_fn(model(inputs),targets))

In [16]:
# Train the model for 100 epochs
fit(100,model,loss_fn,opt, train_dl)

Training Loss:  tensor(2.0675, grad_fn=<MseLossBackward0>)


In [17]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 55.6942,  70.5632],
        [ 80.3881, 100.9396],
        [116.5804, 133.3322],
        [ 19.8102,  37.2828],
        [100.0154, 119.3722],
        [ 55.6942,  70.5632],
        [ 80.3881, 100.9396],
        [116.5804, 133.3322],
        [ 19.8102,  37.2828],
        [100.0154, 119.3722],
        [ 55.6942,  70.5632],
        [ 80.3881, 100.9396],
        [116.5804, 133.3322],
        [ 19.8102,  37.2828],
        [100.0154, 119.3722]], grad_fn=<AddmmBackward0>)

In [18]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [19]:
from sklearn.metrics import mean_squared_error
print(mean_squared_error(targets.detach().numpy(),preds.detach().numpy()))

2.067546


**Exercise**

In [20]:
#1. Estimate the value of model parameters(weights and bias) and MSE Loss after training for 1000 epochs.
fit(1000, model, loss_fn, opt, train_dl)

Training Loss:  tensor(0.6625, grad_fn=<MseLossBackward0>)


In [21]:
#2. Take the learning rate value as 0.1 and train the model. Write in brief the impact of this learning rate on the model.
model2 = nn.Linear(3,2)

print(model2.weight)
print(model2.bias)

opt2 = torch.optim.SGD(model2.parameters(), lr=0.1)

fit(250, model2, loss_fn, opt2, train_dl)
preds = model2(inputs)

print(preds)
print(targets)

Parameter containing:
tensor([[-0.5073, -0.0906, -0.1844],
        [-0.4193,  0.0320, -0.2525]], requires_grad=True)
Parameter containing:
tensor([ 0.2120, -0.3554], requires_grad=True)
Training Loss:  tensor(nan, grad_fn=<MseLossBackward0>)
tensor([[nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan]], grad_fn=<AddmmBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [22]:
#3. Take the learning rate value as 0.0000001 and train the model. Write in brief the impact of this learning rate on the model.
model3 = nn.Linear(3,2)
opt3 = torch.optim.SGD(model3.parameters(), lr=0.0000001)
fit(250, model3, loss_fn, opt3, train_dl)
preds = model3(inputs)
print(preds)
print(targets)
from sklearn.metrics import mean_squared_error
print(mean_squared_error(targets.detach().numpy(),preds.detach().numpy()))

Training Loss:  tensor(400.7071, grad_fn=<MseLossBackward0>)
tensor([[ 49.1796,  68.8647],
        [ 62.8412,  90.4552],
        [ 97.0061, 119.3511],
        [ 36.1126,  58.5291],
        [ 65.0493,  91.6983],
        [ 49.1796,  68.8647],
        [ 62.8412,  90.4552],
        [ 97.0061, 119.3511],
        [ 36.1126,  58.5291],
        [ 65.0493,  91.6983],
        [ 49.1796,  68.8647],
        [ 62.8412,  90.4552],
        [ 97.0061, 119.3511],
        [ 36.1126,  58.5291],
        [ 65.0493,  91.6983]], grad_fn=<AddmmBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
400.7071


In [23]:
#5. Use the model to predict crop yield for apples if temperature is 70, Rain is 34 and Humidity is 45.
preds = model(torch.FloatTensor([70,34,45]))
preds

tensor([31.9649, 46.6611], grad_fn=<AddBackward0>)